version: '3.0'
services:
  db:
    image: postgres:11-alpine
    restart: always
    volumes: 
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: forum
  app:
    image: blockplane-app
    restart: always
    depends_on:
      - db
